name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          Install-Module powershell-yaml -Force
          Install-Module PSScriptAnalyzer -Force
          Install-Module Pester -Force

      - name: lint
        run: Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning

      - name: unit tests
        run: Invoke-Pester tests -Output Detailed
